server:
    port: 8081
spring:
    application:
        name: hmdp
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/hmdp?useSSL=false&serverTimezone=UTC
        username: root
        password: 1107
    redis:
        host: 192.168.142.128
        port: 6379
        password: 1107
        lettuce:
            pool:
                max-active: 10
                max-idle: 10
                min-idle: 1
                time-between-eviction-runs: 10s
    jackson:
        default-property-inclusion: non_null # JSON处理时忽略非空字段
mybatis-plus:
    type-aliases-package: com.hmdp.entity # 别名扫描包
logging:
    level:
        com.hmdp: debug
rocketmq:
    name-server: 192.168.142.128:9876
    producer:
        group: voucher-producer-group
        access-key: rocketmq2
        secret-key: 12345678
    consumer:
        group: voucher-consumer-group
        access-key: rocketmq2
        secret-key: 12345678
